version: 2
jobs:
    build-live:
        branches:
            only:
                - master
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - deploy:
                name: digital-ocean
                command: ssh -o "StrictHostKeyChecking no" danconable@104.248.64.221 "cd ~/AdanConstanzo; git pull; npm install;"
    build-stage:
        branches:
            only:
                - stage
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - deploy:
                name: digital-ocean
                command: ssh -o "StrictHostKeyChecking no" danconable@104.248.64.221 "cd ~/AdanConstanzoStage; git checkout stage; pull origin stage; npm install;"
