version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
    build-live:
        machine:
            enabled: true
        steps:
            - deploy:
                name: digital-ocean-live
                command: ssh -o "StrictHostKeyChecking no" danconable@104.248.64.221 "cd ~/AdanConstanzo; git pull; npm install;"
    build-stage:
        machine:
            enabled: true
        steps:
            - deploy:
                name: digital-ocean-stage
                command: ssh -o "StrictHostKeyChecking no" danconable@104.248.64.221 "source /home/danconable/.bashrc; ls /home/danconable/.nvm; "
                # command: ssh -o "StrictHostKeyChecking no" danconable@104.248.64.221 "nvm use 10.16.3; cd ~/AdanConstanzoStage; git checkout stage; git pull origin stage; npm install; npm run build;"

workflows:
  version: 2
  build-and-deploy:
    jobs:
        - build
        - build-live:
            requires:
                - build
            filters:
                branches:
                    only: master
        - build-stage:
            requires:
                - build
            filters:
                branches:
                    only: stage
