version: 2
jobs:
    build:
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - deploy:
                name: digital-ocean
                command: ssh -o "StrictHostKeyChecking no" danconable@104.248.64.221 "cd ~/AdanConstanzo; git pull; npm install;"
